name: rag_assistant
services:
  app:
    build: .
    container_name: rag
    ports:
      - 8501:8501
    volumes:
      - ./app:/rag/app:ro
      - ./data:/rag/data:ro
      - ./vector_store:/rag/vector_store
      - ./requirements.txt:/rag/requirements.txt
      - ./config.yaml:/rag/config.yaml
      - /rag/.venv
